name: Ory Config - Apply Main

on:
  push:
    branches: 
      - main
jobs:
  filter:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      environments: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dev:
              - 'dev/**'
            qa:
              - 'qa/**'
  plan:
    name: Plan
    needs: filter
    uses: ./.github/workflows/ory-plan.yml
    if: needs.filter.outputs.environments != '[]'
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.filter.outputs.environments) }}
      fail-fast: false
    with: 
      environment: ${{ matrix.environment }}
    secrets: inherit

  apply:
    name: Aplly
    needs: [ plan, filter]
    uses: ./.github/workflows/ory-apply.yml
    if: needs.filter.outputs.environments != '[]'
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.filter.outputs.environments) }}
      fail-fast: false
    with: 
      environment: ${{ matrix.environment }}
    secrets: inherit
