name: Ory Apply

on:
  workflow_call:
    inputs:
      environment:
        description: 'The name of the GitHub environment to use as context for this workflow'
        required: true
        type: string

env:
  ORY_PROJECT_ID: ${{ vars.ORY_PROJECT_ID }}
  ORY_WORKSPACE_ID: ${{ vars.ORY_WORKSPACE_ID }}
  ORY_WORKSPACE_API_KEY: ${{ secrets.ORY_WORKSPACE_API_KEY }}
  # expose SMTP to the shell; yq will read it via env()
  SMTP_CONNECTION_URI: ${{ secrets.SMTP_CONNECTION_URI }}
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    container:
      image: oryd/ory:v1
      options: --user root # Required so checkout can write to the mounted workspace (default non-root user has no perms)
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup YAML tooling
        run: |
          apk add --no-cache curl
          curl -sSL https://github.com/mikefarah/yq/releases/download/v4.47.2/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Render config with secrets
        run: |
          cp identity.yaml identity.rendered.yaml
          yq -i '.courier.smtp.connection_uri = env(SMTP_CONNECTION_URI)' identity.rendered.yaml

      - name: Apply
        run: |
          ory use project "$ORY_PROJECT_ID"
          ory update identity-config --format yaml --file identity.rendered.yaml
          ory update oauth2-config   --format yaml --file oauth2.yaml
          