name: Ory Config – Plan

on:
  pull_request:
  push:

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: oryd/ory:v1
      options: --user root
    environment: dev
    env:
      ORY_PROJECT_ID: "fae0f954-aa75-490a-afb8-19d573b76a83"
      ORY_WORKSPACE_ID: "32e5b9ac-d811-47ea-8c72-b33e19187b39"
      ORY_WORKSPACE_API_KEY: ${{ secrets.ORY_WORKSPACE_API_KEY }}
      # expose SMTP to the shell; yq will read it via env()
      SMTP_CONNECTION_URI: ${{ secrets.SMTP_CONNECTION_URI }}
    defaults:
      run:
        working-directory: dev
    steps:
      - uses: actions/checkout@v4
      # ⬇️ Inject the secret into the desired file BEFORE comparing
      - name: Inject secret into identity.yaml
        run: |
          # Updates the single path from env without printing the secret in logs
          yq -i '.courier.smtp.connection_uri = env(SMTP_CONNECTION_URI)' identity.yaml

      - name: Apply config
        run: |
          
