name: Ory Config – Plan

on:
  pull_request:
  push:

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: oryd/ory:v1
      options: --user root
    environment: dev
    env:
      ORY_PROJECT_ID: "fae0f954-aa75-490a-afb8-19d573b76a83"
      ORY_WORKSPACE_ID: "32e5b9ac-d811-47ea-8c72-b33e19187b39"
      ORY_WORKSPACE_API_KEY: ${{ secrets.ORY_WORKSPACE_API_KEY }}
      # expose SMTP to the shell; yq will read it via env()
      SMTP_CONNECTION_URI: ${{ secrets.SMTP_CONNECTION_URI }}
    defaults:
      run:
        working-directory: dev
    steps:
      - uses: actions/checkout@v4
      - name: Fetch current Ory config
        run: |
          ory use project "$ORY_PROJECT_ID"
          ory get identity-config   --format yaml > live.identity.yaml
          ory get oauth2-config     --format yaml > live.oauth2.yaml

      - name: Setup YAML tooling
        run: |
          apk add --no-cache curl
          curl -sSL https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_linux_amd64.tar.gz | tar -xz && mv dyff /usr/local/bin/
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Render config with secrets
        run: |
          cp identity.yaml identity.rendered.yaml
          yq -i '.courier.smtp.connection_uri = env(SMTP_CONNECTION_URI)' identity.rendered.yaml

      - name: Format configs for comparison
        run: |
          # Pretty-print with stable key order for clean diffs
          yq -P 'sort_keys(..)' live.identity.yaml      > live.identity.norm.yaml
          yq -P 'sort_keys(..)' identity.rendered.yaml  > desired.identity.norm.yaml
          yq -P 'sort_keys(..)' live.oauth2.yaml        > live.oauth2.norm.yaml
          yq -P 'sort_keys(..)' oauth2.yaml             > desired.oauth2.norm.yaml
          # Replace originals for the diff step below
          mv live.identity.norm.yaml     live.identity.yaml
          mv desired.identity.norm.yaml  identity.rendered.yaml
          mv live.oauth2.norm.yaml       live.oauth2.yaml
          mv desired.oauth2.norm.yaml    oauth2.yaml

      - name: Show planned changes
        run: |
          echo "===== Identity config diff ====="
          dyff between --color on live.identity.yaml identity.rendered.yaml || true
          echo
          echo "===== OAuth2 config diff ====="
          dyff between --color on live.oauth2.yaml oauth2.yaml || true