name: Ory Config – Plan

on:
  pull_request:
  push: 

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: oryd/ory:v1
      options: --user root
    environment: dev
    env:
      ORY_PROJECT_ID: "fae0f954-aa75-490a-afb8-19d573b76a83"
      ORY_WORKSPACE_ID: "32e5b9ac-d811-47ea-8c72-b33e19187b39"
      ORY_WORKSPACE_API_KEY: ${{ secrets.ORY_WORKSPACE_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Export live config (YAML)
        run: |
          ory get identity-config --format yaml > live.identity.yaml
          ory get oauth2-config --format yaml > live.oauth2.yaml
          ory get permission-config --format yaml > live.permissions.yaml || true

      - name: Install dyff & yq
        run: |
          apk add --no-cache curl
          curl -sSL https://github.com/homeport/dyff/releases/download/v1.7.0/dyff_1.7.0_linux_amd64.tar.gz | tar -xz && mv dyff /usr/local/bin/
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Normalize YAML (optional)
        run: |
          for f in *.yaml live.*.yaml; do
            [ -f "$f" ] || continue
            yq -P "$f" > "$f.norm" && mv "$f.norm" "$f"
          done

      - name: Show plan (semantic YAML diff)
        run: |
          echo "::group::Identity"
          dyff between live.identity.yaml identity.yaml || true
          echo "::endgroup::"
          echo "::group::OAuth2"
          dyff between live.oauth2.yaml   oauth2.yaml   || true
          echo "::endgroup::"
          echo "::group::Permissions"
          if [ -f permissions.yaml ] && [ -f live.permissions.yaml ]; then
            dyff between live.permissions.yaml permissions.yaml || true
          else
            echo "Permissions: no desired or live config to diff."
          fi
          echo "::endgroup::"

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ory-plan
          path: |
            live.identity.yaml
            live.oauth2.yaml
            live.permissions.yaml
